### ISSUE TITLE
Problem with CSV export for recurring events

### ISSUE THREAD

**Issue by selasphorus** [ajrosen/icalPal#10]
Hi Andy -- CSV export is working now, thank you! but there's still a small problem with the exports -- please see below.

Recurring events export with misaligned data:
- the 'daynum' column contains the designated end date for the series
- the 'stime' column contains the sday value
- the stime value is displaced into the 'etime' column
- the etime value lands in the 'sday' column

See screenshot of sample csv data, attached
![Screenshot 2024-03-30 at 13 14 48](https://github.com/ajrosen/icalPal/assets/56554427/ef6ef903-57d2-4551-9d3a-cae58b3d1cfe)

**Comment by selasphorus** [comment]
I've been limiting the results to specific calendars, and setting the date format, like so:
`icalPal events --from 20240301 --to 20240331  --ic 'Performing Arts' -o csv > test-240402-1.csv --df %Y-%m-%d`

Two additional observations:
1. Initially I ran an export for several calendars at once. When I run separate exports for each calendar, each seems to have a slightly different set of columns. They're all CALDAV calendars associated with my google account, so I can't think why they'd yield such different results.
2. If I try to select only certain columns for export, the additional option has no effect on the output. For example:
`icalPal events --from 20240301 --to 20240331  --ic 'Performing Arts' -o csv > test-240402-1.csv --iep sdate, edate --df %Y-%m-%d`. Maybe I'm using that option incorrectly?

**Comment by ajrosen** [comment]
There are a couple changes you need to make to the command.

1. When saving to a file, the `> test-240402-1.csv` needs to come last. The shell stops reading arguments when it sees the redirection operator, so any options after that are not getting to icalPal.
2. Also change `--iep sdate, edate` to `--iep sdate,edate`.  Remove the space after the comma.

**Comment by ajrosen** [comment]
This is a lot more involved than I anticipated.  I assumed a lot more "magic" in Ruby's CSV class than it actually has.

Also, the machine-readable outputs (csv, hash, json, yaml) always print all fields.  Many options, including --iep, --eep, and --aep, are ignored.  This isn't a problem for hash, json, or yaml; those label every field in every item.  

But CSV has one set of labels (the header row) for all items.  Any item that has different fields than the first one will look wrong.

It'll take some time to fix.  Until then, I suggest using a different format if possible.  Or fix the output manually to align the columns.

**Comment by selasphorus** [comment]
Thanks very much for looking into it. I would offer to help work on a fix, but I'd have to start from scratch learning Ruby and I don't have time for that currently. I wonder how tricky it would be to add an xml output option? I'm trying to streamline a workflow using a particular WP import plugin that only accepts csv and xml files. Perhaps there's a utility for easily converting yaml to xml -- I'll go look -- but it would be super to not have to add another step.

**Comment by ajrosen** [comment]
I've just released version 1.2.0 which fixes CSV output.  Thank you for the bug report!

**Comment by selasphorus** [comment]
Thanks so much! Sorry for the slow reply. I'll try it out today!

**Comment by selasphorus** [comment]
Works like a charm! Thanks again :-)
