### ISSUE TITLE
Did Sequoia 15.1 break icalPal?

### ISSUE THREAD

**Issue by fgombault** [ajrosen/icalPal#25]
I just upgraded my OS to Sequoia 15.1, Calendar.app has changes.
icalpal can no longer find /Users/***/Library/Calendars/Calendar.sqlitedb

This file doesn't seem to exist anymore :-(

**Comment by ajrosen** [comment]
Yeah, that hit me too.  I've just found where it went:

`~/Library/Group Containers/group.com.apple.calendar/Calendar.sqlitedb`

For now you can run `icalpal --db ~/Library/Group\ Containers/group.com.apple.calendar/Calendar.sqlitedb`.  I never thought that option would be so useful.

I'll add some code to check both locations.
