### ISSUE TITLE
--ab option not working

### ISSUE THREAD

**Issue by EphraimSiegfried** [ajrosen/icalPal#5]
Hi, thanks for making icalPal!

I've encountered issues while using the --ab option :

### 1. Error with Empty Argument in `--ab`
- **Command:** `icalPal --ab="" eventsToday`
- **Expected Behavior:** The command should remove the bullets.
- **Actual Behavior:** The command results in an error message `invalid argument: --ab=`.

### 2. Bullets Not Replacing with `--ab="-"`
- **Command:** `icalPal --ab="-" eventsToday`
- **Expected Behavior:** The bullets should get replaced with -
- **Actual Behavior:** The bullets do not get replaced.

**Comment by ajrosen** [comment]
Sorry, I forgot I hadn't pushed a new release.  RubyGem and Gemfury now have version **1.1.4**.

Bullets are fixed by changing the `--ab` option to `--bullet`.

Thanks!
